name: Python ai 

on:
  workflow_dispatch: # 手动触发配置

jobs:
  run-ocr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install  json numpy time openai datetime requests tqdm 

    - name: Run ai script
      run: python main.py
      
    - name: Upload result
      uses: actions/upload-artifact@v4
      with:
        name: ocr-result
        path: result.json
